### ISSUE TITLE
undefined method `normalize_formatting_rules' for #<Money fractional:1000 currency:EUR>

### ISSUE THREAD

**Issue by damienlethiec** [RubyMoney/money-rails#524] opened 2018-04-10 06:26 UTC
Hello there,

I have just created a new Rails 5.2 app and, when I try to use the helper `humanized_money_with_symbol` with a correct Money object, I get the following error:

`undefined method `normalize_formatting_rules' for #<Money fractional:1000 currency:EUR>`

Any clue of the reason? Any fix?

Thanks a ton :)

**Comment by PedroPauloML** [comment] 2018-04-10 15:04
Same error

**Comment by antstorm** [comment] 2018-04-10 18:19
Which version of money are you using? This seems to be caused by the new version on money, however `money-rails` depends on `~> 6.10.0`, which should not include the latest release

**Comment by antstorm** [comment] 2018-04-10 18:57
This has been fixed by #525. Also new version of the gem has been pushed to RubyGems — https://rubygems.org/gems/money-rails (version 1.11.0). Please upgrade and the issue should go away.

**Closed by antstorm** 2018-04-10 18:57 UTC

**Comment by vladprotsevich** [comment] 2020-07-04 10:34
Hi! Did u find a way how to solve that issue? I updated my gem to 1.13.3 but that problem not disappear
