### ISSUE TITLE
Monetizable class - Stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by lucascaton** [RubyMoney/money-rails#401] opened 2015-12-20 09:07 UTC
Hi, I found a problem when setting the `currency_column` config, e.g.:

```ruby
# config/initializers/money.rb
MoneyRails.configure do |config|
  config.default_currency = :aud
  config.currency_column  = { present: false }
end
```

When I do that, I got the following error:

```shell
money-rails-1.4.1/lib/money-rails/active_record/monetizable.rb:199:in `to_s': stack level too deep (SystemStackError)
```

Sometimes (not sure why), this also happens:
```shell
money-rails-1.4.1/lib/money-rails/active_record/monetizable.rb:111:in `public_send': stack level too deep (SystemStackError)
```

My stack:
* Ruby 2.2.4
* Rails 4.2.5
* Gem 1.4.1
* OS X 10.11.2 (El Capitan)

**Comment by lucascaton** [comment] 2015-12-20 09:09
Aditional info:

* PostgreSQL 9.4.5

My migration:

```ruby
create_table :transactions do |t|
  # ...  
  t.monetize :amount, null: false
end
```

My model:

```ruby
monetize :amount_cents, allow_nil: false, numericality: { greater_than_or_equal_to: 0 }
```

Although I tried only `monetize :amount_cents` and got the same errors.

**Comment by longkt90** [comment] 2015-12-26 08:21
I have same errors when switching from rails 4.1 to rails 4.2.5. It works normally with rails 4.1
```
.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/money-rails-1.4.1/lib/money-rails/active_record/monetizable.rb:210:in `block (2 levels) in monetize'
.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/money-rails-1.4.1/lib/money-rails/active_record/monetizable.rb:114:in `public_send'
```

any suggestion?

**Comment by longkt90** [comment] 2015-12-26 08:33
My problem is solved with current codes in master (revision: c8b09ad5074557e509e662357681cb0f3b5e57a3)

@lucascaton you should check it out

**Comment by lucascaton** [comment] 2015-12-28 00:54
@longkt90 thanks!

**Comment by antstorm** [comment] 2016-04-28 19:20
Closing this, because it doesn't seem to be reproducible in `master`. Please reopen in case I'm wrong.

**Closed by antstorm** 2016-04-28 19:20 UTC
