### ISSUE TITLE
incorrect validation price greater than another price

### ISSUE THREAD

**Issue by ZombieHarvester** [RubyMoney/money-rails#368] opened 2015-09-11 22:23 UTC
Product has price and retail price. Retail price must be greater than price
gem 'money-rails',    '1.4.1'

```ruby
class Product < ActiveRecord::Base
  monetize  :price_cents,        numericality: { greater_than: 0       }
  monetize  :retail_price_cents, numericality: { greater_than: :price  }
end

p = Product.new price: 10, retail_price: 15
p.valid?
p.errors
    :retail_price => [ [0] "must be greater than 10.00" ]
p.retail_price > p.price
    true
p.retail_price > 10.00
    true
```

i believe the example above supposed to be working, please correct me if i'm wrong. Below is my workarround, now validations work as expected

```ruby
monetize  :price_cents,        numericality: { greater_than: 0                                  }
monetize  :retail_price_cents, numericality: { greater_than: ->(product) { product.price.to_d } }
```

**Comment by fotos** [comment] 2015-09-15 08:36
@ZombieHarvester we recently stumbled upon a similar case in a recent project.

Basically [`MoneyValidator`](https://github.com/RubyMoney/money-rails/blob/v1.4.1/lib/money-rails/active_model/validator.rb#L3) is a subclass of `NumericalityValidator` and it [delegates to the superclass](https://github.com/RubyMoney/money-rails/blob/v1.4.1/lib/money-rails/active_model/validator.rb#L37) the handling of comparisons such as `:greater_than`.

If you use a `:symbol`, it is [sent to the record](https://github.com/rails/rails/blob/4-2-stable/activemodel/lib/active_model/validations/numericality.rb#L55) and you get back a `Money` object. This money object is [then compared](https://github.com/rails/rails/blob/4-2-stable/activemodel/lib/active_model/validations/numericality.rb#L58) to the raw value. The raw value is (wrongly) coerced to Money and you get an invalid comparison.

In your case, `:retail_price_cents` (as cents) is compared to `price` (`Money`).
Short demonstration of what happens:

```Ruby
> p.price
=> 10 #<Money fractional:1000 currency:EUR>
> p.retail_price
=> 15 #<Money fractional:1500 currency:EUR>
```

Now when you validate the following comparison is made:

```Ruby
> 15 > p.price # Money object
=> false
```

`15` is coerced to Money as:

```Ruby
> Money.new(15)
=> #<Money fractional:15 currency:EUR>
```

Which as you can see is less than `#<Money fractional:1000 currency:EUR>`

The coercion issue has been discussed extensively in rubymoney/money#404. Right now `Proc` is the recommended workaround, which compares `decimal` values properly.

For the record, our workaround was similar:

```Ruby
validates :revenue_start,
  'money_rails/active_model/money' => { less_than: ->(record) { record.revenue_end.amount } }
```

but instead we used `#amount`, which is equivalent to `#to_d`.

This is not a bug of `money-rails` per se, therefore I'm closing this issue. If you have a proposed PR, a workaround for `MoneyValidator` or you simply disagree, feel free to comment and we'll reopen this issue.

**Closed by fotos** 2015-09-15 08:36 UTC

**Comment by ZombieHarvester** [comment] 2015-09-15 18:11
@fotos would be nice to have this workaround mentioned in the readme until it works as expected. Thanks

**Comment by fotos** [comment] 2015-09-15 18:18
Certainly worth a mention. Feel free to open a PR. Perhaps a new section,
Caveats?

-fotos

**Comment by ZombieHarvester** [comment] 2015-09-15 20:16
@fotos, by the way the following is very frustrating 

```ruby
p.price = 10
=> 10

p.price
=> #<Money fractional:1000 currency:USD>

p.price > 5
=> true

5 < p.price
=> false
```

money object was supposed to solve float rounding issues but actually introduces issues of its own

**Comment by fotos** [comment] 2015-09-15 20:50
@ZombieHarvester I wholeheartedly agree about the frustration part. There is an open PR rubymoney/money#535 that will prevent all coerced operations except multiplication.

If you think about it, comparison between `Money` and `Numeric` (superclass of `Integer`) doesn't make much sense. What does 5 represent in the comparison above? Cents? Whole dollars?

If the operation is not [commutative](https://en.wikipedia.org/wiki/Commutative_property) then the coersion will be wrong, and unfortunately most operations are not commutative.

In my opinion, `Money` is still the recommended way to handle money in Ruby. It solves more problems than it introduces. Just avoid comparisons (or all operations) between Money and other objects, such as Integers, or at least take care to explicitly convert them to Money as well.

If you open that PR about the caveats, we could mention that as well.

**Comment by ZombieHarvester** [comment] 2015-09-15 21:58
@fotos, 5 would represent dollars, cents i'd compare with price_cents. 

I'd agree about money object if I used Money gem directly. But with `monetize` helper I was expecting a virtual attribute with more transparent and predictable interface (like specialized numeric plus related presenters) that would work fine with other numerics

i also noticed `monetize` helper didn't like store accessor attribute (postgres json column). This is another story but together with comparison issue it adds up to not so transparent interface

**Comment by fotos** [comment] 2015-09-16 08:03
@ZombieHarvester thank you for your feedback, we'll certainly try to make `money` integration more transparent and easier to use in the future. You can contribute as well if you want.

I'll open the PR with the caveats.

**Comment by ZombieHarvester** [comment] 2015-09-16 14:40
@fotos thanks!

**Comment by KelseyDH** [comment] 2018-02-01 12:03
I was able to get this validation setup working when I tried:

```ruby
class Transfer < ApplicationRecord
  validate ValidateUtil.amount
end

# app/models/concerns/validate_util.rb
module ValidateUtil
  mattr_accessor :amount

  def self.amount(amount_attribute = :amount)
    Proc.new do |object|
      password                = object.send(amount_attribute)

      if amount.present?
        if Money.new(10, "CAD") > amount
          object.errors.add(:amount, I18n.t("validators.bad_amount"))
        elsif Money.new(990000, "CAD") < amount
          object.errors.add(:amount, I18n.t("validators.bad_amount"))
        end
      end
    end
  end
end
```

Making sure to put the `Money` object first before the numerical comparison on `amount`, to avoid gotchas as pointed out by @ZombieHarvester .
