### ISSUE TITLE
NameError: instance variable @_currency not defined

### ISSUE THREAD

**Issue by juzerali** [RubyMoney/money-rails#589] opened 2019-12-12 09:45 UTC
We have a high throughput application ~21k RPM. We are facing an issue with validator. About 1% of requests raises `NameError: instance variable @_currency not defined` at [this line](https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_model/validator.rb#L59).

Gemfile
`gem 'money-rails', '~>1.13'`

From the code it seems this error should never get raised, since it performs a `instance_variable_defined?` check. But somehow our error stack is filled with NameError's emanating from this line. I guess a rescue block can solve this issue temporarily for us.

**Comment by antstorm** [comment] 2019-12-14 12:07
@juzerali appreciate the PR, but I'd love a proper fix for the issue. Can you post a stack trace of the error here so I can have a look at the possible cause?

I suspect a race condition where the instance variable is present at the condition time, but is already removed by another thread before `remove_instance_variable` call

**Comment by dgp** [comment] 2019-12-16 09:33
@antstorm, here is the stack trace. this is happening intermediately. 
org/jruby/RubyKernel.java:2239:in `remove_instance_variable'…rails-1.13.3/lib/money-rails/active_model/validator.rb:   59:in `block in reset_memoized_variables!'org/jruby/RubyArray.java:1792:in `each'…rails-1.13.3/lib/money-rails/active_model/validator.rb:   56:in `reset_memoized_variables!'…rails-1.13.3/lib/money-rails/active_model/validator.rb:    5:in `validate_each'…0/gems/activemodel-5.2.3/lib/active_model/validator.rb:  152:in `block in validate'org/jruby/RubyArray.java:1792:in `each'…0/gems/activemodel-5.2.3/lib/active_model/validator.rb:  149:in `validate'…ms/activesupport-5.2.3/lib/active_support/callbacks.rb:  426:in `block in make_lambda'…ms/activesupport-5.2.3/lib/active_support/callbacks.rb:  198:in `block in halting'…ms/activesupport-5.2.3/lib/active_support/callbacks.rb:  606:in `block in default_terminator'org/jruby/RubyKernel.java:1181:in `catch'…ms/activesupport-5.2.3/lib/active_support/callbacks.rb:  605:in `block in default_terminator'…ms/activesupport-5.2.3/lib/active_support/callbacks.rb:  199:in `block in halting'…ms/activesupport-5.2.3/lib/active_support/callbacks.rb:  513:in `block in invoke_before'org/jruby/RubyArray.java:1792:in `each'…ms/activesupport-5.2.3/lib/active_support/callbacks.rb:  513:in `invoke_before'…ms/activesupport-5.2.3/lib/active_support/callbacks.rb:  131:in `run_callbacks'…ms/activesupport-5.2.3/lib/active_support/callbacks.rb:  816:in `_run_validate_callbacks'…gems/activemodel-5.2.3/lib/active_model/validations.rb:  409:in `run_validations!'…emodel-5.2.3/lib/active_model/validations/callbacks.rb:  118:in `block in run_validations!'…ms/activesupport-5.2.3/lib/active_support/callbacks.rb:   98:in `run_callbacks'…ms/activesupport-5.2.3/lib/active_support/callbacks.rb:  816:in `_run_validation_callbacks'…emodel-5.2.3/lib/active_model/validations/callbacks.rb:  118:in `run_validations!'…gems/activemodel-5.2.3/lib/active_model/validations.rb:  339:in `valid?'

**Comment by antstorm** [comment] 2019-12-20 00:29
@dgp I see, this is pretty much expected and doesn't point out the problem. Is there a chance that an instance of this model is shared across different threads?

**Comment by juzerali** [comment] 2019-12-20 13:27
It's a usual web application but with a very high throughput. If I haven't
mentioned already, the peak hour throughput is ~50k rpm. It's possible that
same entity is being referenced from multiple threads. But we don't share
the same instance between threads.

**Comment by antstorm** [comment] 2019-12-30 12:02
@dgp @juzerali can you please paste your model with attribute validation definitions?

From what I can tell — it's very likely caused by a race condition. From the stacktrace it also looks like Rails might be initializing validators ahead of time, which means they are likely to stay around for each instance, so a race condition is possible in a multi-threaded env

**Comment by antstorm** [comment] 2019-12-30 12:10
Oh… ok, digging deeper into Rails' internals — it caches validator instances on a model class :/ Which means that caching anything model-instance specific within a validator is very unsafe as it can potentially override shared data and cause problems. I'll find a solution for this issue, hold on

**Comment by antstorm** [comment] 2019-12-31 00:01
Opened a PR ^, can you please try and test this against your setup to make sure it works as expected

**Comment by juzerali** [comment] 2019-12-31 05:46
@antstorm only way for us to test this is to deploy it to production. Are you sure about the changes in the PR. I see that travis-ci build is failing on the PR.

**Comment by antstorm** [comment] 2020-01-01 20:44
@juzerali pretty sure about the changes (CI failures are unrelated — ActiveSupport accidentally broke ruby < 2.3 support, which should be fixed on their end), but don't wanna put you in the spot so it's your call. Do you have specs in place? Do you support canary deployments?

**Closed** 2020-01-11 16:50 UTC
